### ISSUE TITLE
Unable to find module 'Bluebird'

### ISSUE THREAD

**Issue by starlabs007** [raineorshine/solidity-repl#12]
Recent lint commit: https://github.com/raineorshine/solidity-repl/commit/7ca055b9d9be3b0d7bcd2aaa2266b19e3ccf70af broke solr.

I'm getting this error:
>Error: Cannot find module 'Bluebird'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/solidity-repl/index.js:4:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Specifically this line:
`const Bluebird = require('Bluebird')`
was changed from this originally:
`const bluebird = require('bluebird')`

**Comment by raineorshine** [comment]
Ah, my bad! Didn't notice... not sure how that passed the tests.

I have updated and published to v0.3.2. Will you try now?

**Comment by starlabs007** [comment]
Fixed now. Thank you.
