### ISSUE TITLE
Error: invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go struct field 

### ISSUE THREAD

**Issue by stevekfrey** [raineorshine/solidity-repl#13]
Thanks for making this tool! 

The REPL throws the following error after starting:

```
$ solr
Welcome to the Solidity REPL!
> uint a = 1;
> uint b = 2;
> a + b
Error: invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go struct field SendTxArgs.data of type hexutil.Bytes
    at Object.InvalidResponse (/usr/local/lib/node_modules/solidity-repl/node_modules/web3/lib/web3/errors.js:35:16)
    at /usr/local/lib/node_modules/solidity-repl/node_modules/web3/lib/web3/requestmanager.js:86:36
    at request.onreadystatechange (/usr/local/lib/node_modules/solidity-repl/node_modules/web3/lib/web3/httpprovider.js:110:13)
    at dispatchEvent (/usr/local/lib/node_modules/solidity-repl/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/usr/local/lib/node_modules/solidity-repl/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/solidity-repl/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) 
```

I made sure to globally install and update testrpc: 
```
$ npm install -g ethereumjs-testrpc
$ npm install -g solidity-repl
```

**Comment by raineorshine** [comment]
Thank you! I will take a look as soon as I have time. Or maybe someone else
with some free time can take a stab at it.

**Comment by raineorshine** [comment]
I tried, and unfortunately I cannot reproduce the problem. It works fine for me.
