### ISSUE TITLE
solr exception on launch ...

### ISSUE THREAD

**Issue by nmvega** [raineorshine/solidity-repl#6]
Hello Friends:

I'm getting the following exception on launch of **solr**. I couldn't find anything in my web searches. Any ideas? Possibly an old node version? Thank you in advance! :)

> user@dstorm$ node --version
v4.6.1
> user@dstorm$ js -h
JavaScript-C 1.8.5 2011-03-31
[ ... snip ... ]
> user@dstorm$ npm install -g solidity-repl
> user@dstorm$ solr
> /home/user/.npm-global/lib/node_modules/solidity-repl/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/node_modules/ethereumjs-vm/lib/index.js:29
> function VM (opts = {}) {
>                   ^
> SyntaxError: Unexpected token =
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/home/user/.npm-global/lib/node_modules/solidity-repl/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/node_modules/ethereumjs-vm/lib/hooked.js:6:12)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/home/user/.npm-global/lib/node_modules/solidity-repl/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:4:18)
>     at Module._compile (module.js:409:26)
user@dstorm$

**Comment by nmvega** [comment]
Solved. I upgrade to Fedora 25 (from Fedora 24) which bundles the latest v6.x version of node, and that seems to have corrected the issue. (P.S.... I didn't want to install a second distribution of node manually on Fedora 24 -- messy -- so I just upgraded to O/S, if curious). Thank you.
